### PR TITLE
Batch Upload Customer Fix

### PR DESCRIPTION
**Pull request by NateSwanson7**
Currently only the last customer in an array of customers is uploaded to Zaius with the correct attributes as each iteration through the loop is overwritten by the next.

---
This change is [Reviewable](https://reviewable.io/reviews/zaiusinc/zaius-php-sdk/7)

### CODE REVIEW

**Review by travish — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/zaiusinc/zaius-php-sdk/7)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by travish — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/zaiusinc/zaius-php-sdk/7)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by cBrenDev** [comment]
@NateSwanson7 good catch and thanks for the clear PR!

We've merged this into develop and will be releasing a 1.0.1 version with just this fix shortly.

**Comment by NateSwanson7** [comment]
@cBrenDev Thank you.

**Comment by NateSwanson7** [comment]
@cBrenDev Can you please add a new tag for 1.0.1 so the updated package is available via Packagist. I'm using the composer package in a project of mine and using `dev-master` or any git branch can sometimes cause compatibility issues with other composer packages.  

Thanks

**Comment by cBrenDev** [comment]
@NateSwanson7 Sorry for the delay, thought we already had. It's up now.

**Comment by NateSwanson7** [comment]
@cBrenDev no worries, thank you for adding the tag.

**Pull request merged**
